### ISSUE TITLE
ios input component . When the input is too long, cannot move the cursor to the starting position by pressing the keyboard.

### ISSUE THREAD

**Issue by HereSinceres** [ant-design/ant-design-mobile#2685] opened 2018-06-28 11:47 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.1

### Environment
ios safari

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/input-item?lang=en-US#input-item-demo-0](https://mobile.ant.design/kitchen-sink/components/input-item?lang=en-US#input-item-demo-0)

### Steps to reproduce
- input long text.
- pressing the keyboard move the cursor to the starting position

### What is expected?
cursor can move to start position

### What is actually happening?
can not

**Comment by micooz** [comment] 2018-07-03 02:22
Cannot reproduce on ios safari, maybe duplicate of #2286

**Comment by awmleer** [comment] 2021-11-17 06:38
v2 is no longer maintained. Please consider upgrading to v5.

**Closed by awmleer** 2021-11-17 06:38 UTC
