### ISSUE TITLE
在严格模式下使用Slider组件开启popover属性会出现警告

### ISSUE THREAD

**Issue by ikangjie** [ant-design/ant-design-mobile#5636] opened 2022-09-03 01:17 UTC
### Version of antd-mobile

antd-mobile 5.22.0  react 17.0.2

### Operating system and its version

iOS

### Browser and its version

chrome 104.x

### Relevant log output

```shell
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Wrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node.react_devtools_backend.js:4026
```

**Comment by miracles1919** [comment] 2022-09-03 02:17
Duplicate of #5154

**Closed by miracles1919** 2022-09-03 02:17 UTC
Labels: bug
